import { GoogleGenAI } from "@google/genai";
import OpenAI from "openai";
import Anthropic from "@anthropic-ai/sdk";
import Groq from "groq-sdk";

export interface PromptfooVar {
  key: string;
  value: string;
}

export interface PromptfooAssertion {
  type: 'contains' | 'not-contains' | 'contains-any' | 'llm-rubric';
  value: string;
}

export interface PromptfooTestCase {
  id: string;
  name: string;
  vars: Record<string, string>;
  assert: PromptfooAssertion[];
}

export interface PromptfooResult {
  promptId: string;
  testCaseId: string;
  promptText: string;
  output: string;
  latencyMs: number;
  success: boolean;
  assertionResults: {
    type: string;
    expected: string;
    actual: string;
    success: boolean;
    reasoning?: string;
  }[];
}

// Low-level client text generation function supporting any of the configured API providers
async function generateText(
  provider: string,
  prompt: string,
  apiKeys: Record<string, string>
): Promise<string> {
  const p = provider.toLowerCase();
  
  if (p === 'gemini') {
    const key = (apiKeys.gemini || process.env.GEMINI_API_KEY || "").trim();
    if (!key) throw new Error("Gemini API Key is missing. Please add it via the Settings drawer first.");
    const ai = new GoogleGenAI({ apiKey: key });
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
    });
    return response.text || "";
  }
  
  if (p === 'openai') {
    const key = (apiKeys.openai || process.env.OPENAI_API_KEY || "").trim();
    if (!key) throw new Error("OpenAI API Key is missing. Please add it via the Settings drawer first.");
    const openai = new OpenAI({ apiKey: key, dangerouslyAllowBrowser: true });
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [{ role: "user", content: prompt }],
    });
    return response.choices[0].message.content || "";
  }
  
  if (p === 'anthropic') {
    const key = (apiKeys.anthropic || process.env.ANTHROPIC_API_KEY || "").trim();
    if (!key) throw new Error("Anthropic API Key is missing. Please add it via the Settings drawer first.");
    const anthropic = new Anthropic({ apiKey: key, dangerouslyAllowBrowser: true });
    const response = await anthropic.messages.create({
      model: "claude-3-5-sonnet-latest",
      max_tokens: 2048,
      messages: [{ role: "user", content: prompt }],
    });
    return response.content[0].type === 'text' ? response.content[0].text : "";
  }
  
  if (p === 'deepseek') {
    const key = (apiKeys.deepseek || process.env.DEEPSEEK_API_KEY || "").trim();
    if (!key) throw new Error("DeepSeek API Key is missing. Please add it via the Settings drawer first.");
    const openai = new OpenAI({ 
      apiKey: key, 
      baseURL: "https://api.deepseek.com",
      dangerouslyAllowBrowser: true
    });
    const response = await openai.chat.completions.create({
      model: "deepseek-chat",
      messages: [{ role: "user", content: prompt }],
    });
    return response.choices[0].message.content || "";
  }

  if (p === 'perplexity') {
    const key = (apiKeys.perplexity || process.env.PERPLEXITY_API_KEY || "").trim();
    if (!key) throw new Error("Perplexity API Key is missing. Please add it via the Settings drawer first.");
    const openai = new OpenAI({ 
      apiKey: key, 
      baseURL: "https://api.perplexity.ai",
      dangerouslyAllowBrowser: true
    });
    const response = await openai.chat.completions.create({
      model: "sonar",
      messages: [{ role: "user", content: prompt }],
    });
    return response.choices[0].message.content || "";
  }

  if (p === 'groq') {
    const key = (apiKeys.groq || process.env.GROQ_API_KEY || "").trim();
    if (!key) throw new Error("Groq API Key is missing. Please add it via the Settings drawer first.");
    const groq = new Groq({ apiKey: key, dangerouslyAllowBrowser: true });
    const response = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [{ role: "user", content: prompt }],
    });
    return response.choices[0].message.content || "";
  }

  throw new Error(`Unsupported provider config: ${provider}`);
}

// Highly resilient judgment engine for custom LLM Rubric validation checks
async function runLlmJudge(
  promptText: string,
  output: string,
  rubric: string,
  provider: string,
  apiKeys: Record<string, string>
): Promise<{ pass: boolean; reasoning: string }> {
  const rubricPrompt = `You are an AI-as-a-judge prompt evaluation agent. 
You are evaluating the target output against a specific semantic grading rubric.

Target Prompt Sent to LLM:
----------------------------------
${promptText}

Output Generated by LLM:
----------------------------------
${output}

Evaluation Rubric:
----------------------------------
${rubric}

You must decide whether the output satisfies the rubric guidelines. Explain your objective evaluation step-by-step, then state your final pass/fail verdict.
Return your response EXACTLY as a JSON object with this shape:
{
  "reasoning": "step-by-step details explaining why it passes or fails",
  "pass": true (or false)
}`;

  // Try Gemini judge if key is available
  const hasGemini = !!(apiKeys.gemini || process.env.GEMINI_API_KEY);
  if (hasGemini) {
    try {
      const key = (apiKeys.gemini || process.env.GEMINI_API_KEY || "").trim();
      const ai = new GoogleGenAI({ apiKey: key });
      const gradingRes = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: rubricPrompt,
        config: {
          responseMimeType: "application/json"
        }
      });
      const text = gradingRes.text || "{}";
      const parsed = JSON.parse(text.replace(/```json\n?|\n?```/g, "").trim());
      return {
        pass: !!parsed.pass,
        reasoning: parsed.reasoning || "Evaluation complete via LLM judge."
      };
    } catch (e) {
      console.warn("Gemini Judge failed, falling back to active provider:", e);
    }
  }

  // Fallback of judge based on selected runtime provider
  const p = provider.toLowerCase();
  let rawText = "{}";
  try {
    if (p === 'openai' || p === 'deepseek' || p === 'perplexity') {
      const key = apiKeys[p] || "";
      const baseURL = p === 'deepseek' ? "https://api.deepseek.com" : p === 'perplexity' ? "https://api.perplexity.ai" : undefined;
      const modelName = p === 'deepseek' ? "deepseek-chat" : p === 'perplexity' ? "sonar" : "gpt-4o";
      const openai = new OpenAI({ apiKey: key, baseURL, dangerouslyAllowBrowser: true });
      const response = await openai.chat.completions.create({
        model: modelName,
        messages: [{ role: "user", content: rubricPrompt }],
        response_format: { type: "json_object" }
      });
      rawText = response.choices[0].message.content || "{}";
    } else {
      rawText = await generateText(provider, rubricPrompt, apiKeys);
    }

    const cleanText = rawText.replace(/```json\n?|\n?```/g, "").trim();
    const parsed = JSON.parse(cleanText);
    return {
      pass: !!parsed.pass,
      reasoning: parsed.reasoning || "Evaluation completed."
    };
  } catch (err: any) {
    const passMatch = rawText.match(/"pass"\s*:\s*(true|false)/i);
    const pass = passMatch ? passMatch[1].toLowerCase() === 'true' : rawText.toLowerCase().includes('"pass": true');
    return {
      pass,
      reasoning: `Judge Fallback (JSON extraction error: ${err.message || err}). Output: ${rawText.substring(0, 150)}...`
    };
  }
}

export async function runPromptfooEvaluation(
  provider: string,
  prompts: { id: string; text: string }[],
  tests: PromptfooTestCase[],
  apiKeys: Record<string, string>,
  onProgress?: (current: number, total: number, message: string) => void
): Promise<PromptfooResult[]> {
  const results: PromptfooResult[] = [];
  const totalRuns = prompts.length * tests.length;
  let runIndex = 0;

  for (const prompt of prompts) {
    for (const testCase of tests) {
      runIndex++;
      if (onProgress) {
        onProgress(
          runIndex,
          totalRuns,
          `Running Prompt "${prompt.id}" on Test "${testCase.name || testCase.id}" using [${provider}]...`
        );
      }

      // 1. Substitute vars into prompt template
      let promptText = prompt.text;
      for (const [key, val] of Object.entries(testCase.vars)) {
        const regex = new RegExp(`{{\\s*${key}\\s*}}`, 'g');
        promptText = promptText.replace(regex, val);
      }

      const startTime = Date.now();
      let output = "";
      let errorMsg = "";

      try {
        output = await generateText(provider, promptText, apiKeys);
      } catch (err: any) {
        console.error("Prompt evaluation run error:", err);
        errorMsg = err.message || "Failed to generate AI response";
        output = `Error: ${errorMsg}`;
      }

      const latencyMs = Date.now() - startTime;

      // 2. Evaluate assertions
      const assertionResults: {
        type: string;
        expected: string;
        actual: string;
        success: boolean;
        reasoning?: string;
      }[] = [];

      let overallSuccess = true;

      if (errorMsg) {
        overallSuccess = false;
        assertionResults.push({
          type: "system",
          expected: "Successful generation",
          actual: "API Error",
          success: false,
          reasoning: errorMsg,
        });
      } else {
        for (const assertion of testCase.assert) {
          let success = false;
          let reasoning = "";

          switch (assertion.type) {
            case 'contains':
              success = output.toLowerCase().includes(assertion.value.toLowerCase());
              reasoning = success 
                ? `Found expected substring: "${assertion.value}"`
                : `Could not find expected substring: "${assertion.value}"`;
              break;

            case 'not-contains':
              success = !output.toLowerCase().includes(assertion.value.toLowerCase());
              reasoning = success
                ? `Successfully verified absence of: "${assertion.value}"`
                : `Unwanted substring found: "${assertion.value}"`;
              break;

            case 'contains-any': {
              const values = assertion.value.split(',').map(v => v.trim()).filter(Boolean);
              success = values.some(val => output.toLowerCase().includes(val.toLowerCase()));
              reasoning = success
                ? `Found at least one matching key: ${values.filter(val => output.toLowerCase().includes(val.toLowerCase())).join(", ")}`
                : `Missing all requested keys: ${assertion.value}`;
              break;
            }

            case 'llm-rubric':
              try {
                const judgeResult = await runLlmJudge(promptText, output, assertion.value, provider, apiKeys);
                success = judgeResult.pass;
                reasoning = judgeResult.reasoning;
              } catch (gradeErr: any) {
                console.error("LLM rubric evaluation fail:", gradeErr);
                success = false;
                reasoning = `LLM rubric judge failed: ${gradeErr.message || gradeErr}`;
              }
              break;
          }

          if (!success) {
            overallSuccess = false;
          }

          assertionResults.push({
            type: assertion.type,
            expected: assertion.value,
            actual: assertion.type === 'llm-rubric' ? 'Semantic evaluation' : (output.length > 50 ? `${output.substring(0, 50)}...` : output),
            success,
            reasoning,
          });
        }
      }

      results.push({
        promptId: prompt.id,
        testCaseId: testCase.id,
        promptText,
        output,
        latencyMs,
        success: overallSuccess,
        assertionResults,
      });
    }
  }

  return results;
}

export function exportPromptfooYaml(
  provider: string,
  prompts: { id: string; text: string }[],
  tests: PromptfooTestCase[]
): string {
  const p = provider.toLowerCase();
  let yamlProvider = "gemini:gemini-3.5-flash";
  if (p === 'openai') yamlProvider = "openai:gpt-4o";
  else if (p === 'anthropic') yamlProvider = "anthropic:claude-3-5-sonnet";
  else if (p === 'deepseek') yamlProvider = "openai:deepseek-chat";
  else if (p === 'perplexity') yamlProvider = "openai:sonar";
  else if (p === 'groq') yamlProvider = "openai:llama-3.3-70b-versatile";

  let yaml = `# Promptfoo Evaluation Config
# Run local using command: npx promptfoo@latest eval -c promptfoo.yaml

prompts:
${prompts.map(p => `  - |
${p.text.split('\n').map(l => `      ${l}`).join('\n')}`).join('\n')}

providers:
  - ${yamlProvider}

tests:
${tests.map(t => {
  let testStr = `  - vars:\n`;
  for (const [k, v] of Object.entries(t.vars)) {
    const sanitizedVal = v.replace(/"/g, '\\"').replace(/\n/g, '\\n');
    testStr += `      ${k}: "${sanitizedVal}"\n`;
  }
  if (t.assert && t.assert.length > 0) {
    testStr += `    assert:\n`;
    for (const ass of t.assert) {
      if (ass.type === 'contains' || ass.type === 'not-contains') {
        testStr += `      - type: ${ass.type}\n        value: "${ass.value.replace(/"/g, '\\"')}"\n`;
      } else if (ass.type === 'contains-any') {
        testStr += `      - type: select-first\n        value: [${ass.value.split(',').map(x => `"${x.trim().replace(/"/g, '\\"')}"`).join(', ')}]\n`;
      } else if (ass.type === 'llm-rubric') {
        testStr += `      - type: llm-rubric\n        value: "${ass.value.replace(/"/g, '\\"')}"\n`;
      }
    }
  }
  return testStr;
}).join('\n')}
`;
  return yaml;
}
